name: boruto scraper

on: [workflow_dispatch]
  #schedule:
   # - cron: '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libnss3 libgconf-2-4

      - name: Install Chromium and Chromedriver
        run: |
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y chromium-chromedriver
          # Remove any old symbolic links to chromedriver
          sudo rm /usr/bin/chromedriver
          # Create a new symbolic link to the installed chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
          # Check if chromium and chromedriver are installed correctly
          google-chrome --version
          chromedriver --version

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main script
        run: python main.py

      - name: Commit changes
        uses: studentAutomations/automatic-changes@v4
        with:
          commit_message: Update novosti.md
        id: auto-commit-action      

      - name: Discord bot notification
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        env:
          WEBHOOK_MAIN: ${{ secrets.WEBHOOK_MAIN }}
        run: python discordBOT.py
